spring:
  application:
    name: FeignApplication
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: null
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  security:
    user:
      name: andre
      password: 123
  sql:
    init:
      mode: always
jwt:
  private:
    key: classpath:private_key.pem
  public:
    key: classpath:public_key.pem